Pg10
ome/ansible-role-postgresql pull request #14
Opened 2018-12-13 23:00 UTC by jburel

Add support for postgresql 10

2018-12-18 10:04 UTC, sbesson reviewed
A few comments/suggestions about how to reduce some logic in the `molecule` tests in order to better cope for the increasing number of versions/parameters combinations.

Overall the main changes are pretty straighforward. Are you proposing to release this change as `3.1.0` given the absence of breaking change?

2018-12-18 10:04 UTC, sbesson commented on molecule/default/tests/test_postgresql_10.py
> +testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
Is it correct there is no difference between these tests and https://github.com/openmicroscopy/ansible-role-postgresql/blob/master/molecule/default/tests/test_postgresql_96.py except for the version parsing?

Is it possible to set up `molecule` configuration so that these are managed via `group_vars` rather than `host_vars` and have a single test running on all hosts under the group?

```
```

2018-12-18 10:04 UTC, sbesson commented on molecule/default/tests/test_server.py
> +    if hostname.startswith('postgresql-1'):
Wonder if we can simplify this logic by setting the hostname as `postgresql-9.4-all`, `postgresql-10-all` etc

2018-12-18 10:04 UTC, sbesson commented on vars/main.yml
> +  setup:
I hadn't realized that they introduced a variation in the naming scheme. If https://github.com/openmicroscopy/ansible-role-postgresql/pull/14/files#diff-2444ad0870f91f17ca6c2a5e96b26823R44 is the only usage, maybe we want this new dictionary to reflect the full command name i.e. `postgresql94-setup`, `postgresql-10-setup` rather just the basename of the setup command.

2018-12-19 16:29 UTC, manics reviewed
Apart from a potential issue with hostnames, looks fine.

2018-12-19 16:29 UTC, manics commented on molecule/default/molecule.yml
> +  - name: postgresql-9.4-all
This could lead to confusion since the `.` separates the host from the domain, i.e. the hostname is `postgresql-9`. On the other hand travis seems to be passing.

2018-12-19 16:49 UTC, sbesson commented on molecule/default/molecule.yml
> +  - name: postgresql-9.4-all
Good point. If we would to reduce confusion but maintain minimal logic in the tests, other options would be to:
- use a different separator e.g. `_` and update the regexp
- find a way to introspect the inventory variables in the tests and directly read postgresql_version` 

I have not investigated the second option and I don't even know whether it is possible.

2018-12-19 16:56 UTC, manics commented on molecule/default/molecule.yml
> +  - name: postgresql-9.4-all
Easier: check and parse the two cases separately: `9\d` vs `10`. I think it's better to be clearer and have some duplication than trying to automate the handling of all cases and risk incorrectly testing something.

2018-12-20 10:40 UTC, manics commented on molecule/default/molecule.yml
> +  - name: postgresql-9.4-all
Another option which is even easier for someone to check for correctness, use a lookup table:
```python
ver_lookup = {
    'postgresql-9.4-all': '9.4',
    'postgresql-95-localhost': '9.5',
    ...
    'postgresql-10-all': '10',
}
ver = ver_lookup[hostname]
```

2018-12-20 15:45 UTC, jburel commented on molecule/default/molecule.yml
> +  - name: postgresql-9.4-all
I have refactored the tests to use lookup

2018-12-20 15:58 UTC, manics requested changes
```
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.14, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
    rootdir: /home/travis/build/openmicroscopy/ansible-role-postgresql/molecule/default, inifile:
    plugins: testinfra-1.16.0
collected 130 items                                                            
    
    tests/test_postgresql_95_96.py ss                                        [  1%]
    tests/test_postgresql_94.py sss                                          [  3%]
    tests/test_server.py ............                                        [ 13%]
    tests/test_create.py ............                                        [ 22%]
    tests/test_noserver.py .                                                 [ 23%]
    tests/test_privileges.py ............................................... [ 59%]
    .................................................                        [ 96%]
    tests/test_extra_options.py ....                                         [100%]
    
    =================== 125 passed, 5 skipped in 116.34 seconds ====================
```
`tests/test_postgresql_95_96.py` and `tests/test_postgresql_94.py` are currently skipped.

2018-12-20 15:58 UTC, manics commented on molecule/default/tests/test_postgresql_94.py
> +    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('postgresql-9.4-*')
Revert this, at the moment this file matches no hosts.

2018-12-20 15:58 UTC, manics commented on molecule/default/tests/test_postgresql_95_96.py
> +    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('postgresql-9.[56]-*')
Revert this, at the moment this file matches no hosts.

2018-12-20 16:03 UTC, jburel commented
@manics done

2018-12-20 16:14 UTC, jburel commented
```
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.14, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
    rootdir: /home/travis/build/openmicroscopy/ansible-role-postgresql/molecule/default, inifile:
    plugins: testinfra-1.16.0
collected 132 items                                                            
    
    tests/test_postgresql_95_96.py ....                                      [  3%]
    tests/test_postgresql_94.py ...                                          [  5%]
    tests/test_server.py ............                                        [ 14%]
    tests/test_create.py ............                                        [ 23%]
    tests/test_noserver.py .                                                 [ 24%]
    tests/test_privileges.py ............................................... [ 59%]
    .................................................                        [ 96%]
    tests/test_extra_options.py ....                                         [100%]
    
    ========================= 132 passed in 125.48 seconds =========================
Verifier completed successfully.
```

2018-12-20 16:32 UTC, manics approved these changes
Thanks

2018-12-20 16:32 UTC, merged

2019-01-08 09:42 UTC, sbesson commented
Was this tagged/released? Sounds like we could have it as a minor version increment.

2019-01-08 09:54 UTC, jburel commented
It was not tagged.

2019-01-08 13:38 UTC, jburel commented
proposed tag 3.1.0